db-uri = "postgres://authenticator:pgrst@127.0.0.1:5544/crm"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "jwt-secret-somente-para-teste-local-0123456789abcdef"
server-host = "127.0.0.1"
server-port = 3001
db-pool = 5
